<a href="https://colab.research.google.com/github/Soy-code/MachineLearning_with_Python/blob/master/Plotly_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Plotly에서 plotly.express와 plotly.graph_objects를 이용해서 그림을 생성함. <br>
(근데 github에 업로드할 때 plotly의 static한 그래프 이미지가 업로드가 안 됨. 이거 해결해봐야 할 듯)

In [23]:
import plotly.express as px
tips_df = px.data.tips()
tips_df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [24]:
tips_df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [25]:
fig = px.histogram(tips_df, x = "total_bill", y = "tip", 
                   color = "smoker", marginal = "rug", 
                   hover_data = tips_df.columns)  
# hover_data : 데이터의 세부 정보를 추가적으로 보여주는 팝업 정보창 (interactive하게)
fig.update_layout(title_text = "Histogram", title_x = 0.5) 
# title_x = 0.5 : title을 가운데에
fig.show()

In [26]:
fig = px.box(tips_df, x = "time", y = 'tip', color = "sex")
fig.update_layout(title_text = "Boxplot", 
                  title_x = .5, title_y = .5, # plot 가운데에 title 놓음. 
                  title_font_size = 30)
fig.show()

In [27]:
fig = px.violin(tips_df, x = 'sex', y = 'tip', color = 'smoker', 
                box = True, points = "all", hover_data = tips_df.columns)
fig.show()
# violin은 distribution을 대칭적으로 하여 보여주는 그래프. 
# 근데 여기서 box = True 옵션을 넣어줘서 boxplot도 추가됨
# points 또한 넣어줌 

In [28]:
import numpy as np
pop_df = px.data.gapminder()
df_1 = np.unique(pop_df['country'])  # country의 원소의 종류를 보여줌
print(df_1)

['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Australia'
 'Austria' 'Bahrain' 'Bangladesh' 'Belgium' 'Benin' 'Bolivia'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Bulgaria' 'Burkina Faso'
 'Burundi' 'Cambodia' 'Cameroon' 'Canada' 'Central African Republic'
 'Chad' 'Chile' 'China' 'Colombia' 'Comoros' 'Congo, Dem. Rep.'
 'Congo, Rep.' 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba'
 'Czech Republic' 'Denmark' 'Djibouti' 'Dominican Republic' 'Ecuador'
 'Egypt' 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Ethiopia' 'Finland'
 'France' 'Gabon' 'Gambia' 'Germany' 'Ghana' 'Greece' 'Guatemala' 'Guinea'
 'Guinea-Bissau' 'Haiti' 'Honduras' 'Hong Kong, China' 'Hungary' 'Iceland'
 'India' 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Israel' 'Italy' 'Jamaica'
 'Japan' 'Jordan' 'Kenya' 'Korea, Dem. Rep.' 'Korea, Rep.' 'Kuwait'
 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Madagascar' 'Malawi' 'Malaysia'
 'Mali' 'Mauritania' 'Mauritius' 'Mexico' 'Mongolia' 'Montenegro'
 'Morocco' 'Mozambique' 'Myanmar

In [29]:
df_korea = pop_df.query("country == 'Korea, Rep.'")
df_korea.head()  # 한국의 경우만을 출력

country continent  year  ...    gdpPercap  iso_alpha  iso_num
840  Korea, Rep.      Asia  1952  ...  1030.592226        KOR      410
841  Korea, Rep.      Asia  1957  ...  1487.593537        KOR      410
842  Korea, Rep.      Asia  1962  ...  1536.344387        KOR      410
843  Korea, Rep.      Asia  1967  ...  2029.228142        KOR      410
844  Korea, Rep.      Asia  1972  ...  3030.876650        KOR      410

[5 rows x 8 columns]

In [30]:
fig = px.line(df_korea, x = "year", y = "lifeExp",
              title = "Life Expectancy in Korea")
fig.show()

In [31]:
df_asia = pop_df.query("continent == 'Asia'")
fig = px.line(df_asia, x = "year", y = "lifeExp", color = "country")  # asia 내에서 국가마다
fig.show()

In [32]:
import plotly.graph_objects as go 
X = df_korea['year']
Y = df_korea['lifeExp']
fig = go.Figure(data = go.Scatter(x = X, y = Y))
fig.show()

In [33]:
import numpy as np
import plotly.graph_objects as go
np.random.seed(0)
N = 100 
x1 = np.linspace(0, 10, N)  # 0과 10 사이를 100개로 분할
y1 = 5 + x1 + np.random.randn(N)  # 절편이 5이고 coef가 1인 linear regression.
                                  # 마지막엔 noise를 추가
y2 = x1 + np.random.randn(N) 
y3 = -5 + x1 + np.random.normal(0, 2, N)

fig = go.Figure()
fig.add_trace(go.Scatter(x = x1, y = y1, mode = "lines", name = "line"))
fig.add_trace(go.Scatter(x = x1, y = y2, mode = "lines + markers", name = "line + marker"))
fig.add_trace(go.Scatter(x = x1, y = y3, mode = "markers", name = "marker"))
fig.show()

In [34]:
import numpy as np
import plotly.graph_objects as go
import plotly.offline as pyo

np.random.seed(0)
N = 100

x1, x2 = np.meshgrid(np.linspace(0, 2, N), np.linspace(0, 2, N))  # 각각 N X N의 정방행렬을 만듦
print(x1)
print('--------------------------------------------------------------------------------------')
print(x2)
# 근데 행/열 방향이 다르네

[[0.         0.02020202 0.04040404 ... 1.95959596 1.97979798 2.        ]
 [0.         0.02020202 0.04040404 ... 1.95959596 1.97979798 2.        ]
 [0.         0.02020202 0.04040404 ... 1.95959596 1.97979798 2.        ]
 ...
 [0.         0.02020202 0.04040404 ... 1.95959596 1.97979798 2.        ]
 [0.         0.02020202 0.04040404 ... 1.95959596 1.97979798 2.        ]
 [0.         0.02020202 0.04040404 ... 1.95959596 1.97979798 2.        ]]
--------------------------------------------------------------------------------------
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.02020202 0.02020202 0.02020202 ... 0.02020202 0.02020202 0.02020202]
 [0.04040404 0.04040404 0.04040404 ... 0.04040404 0.04040404 0.04040404]
 ...
 [1.95959596 1.95959596 1.95959596 ... 1.95959596 1.95959596 1.95959596]
 [1.97979798 1.97979798 1.97979798 ... 1.97979798 1.97979798 1.97979798]
 [2.         2.         2.         ... 2.         2.         2.        ]]


In [35]:
y1 = 5 + x1 + 2*x2  # y1 또한 N X N matrix 
y2 = y1.copy() + np.random.normal(0, 2, (N,N))  # y1에다가 추가적으로 noise를 줌

In [36]:
# 얘는 surface를 만듦
surface_1 = go.Surface(x = x1, y = x2, z = y1)  # 3차원 그래프 
# 얘는 scatter를 만듦
surface_2 = go.Scatter3d(x = x1.flatten()[::20],  # x1이 N X N matrix였으니까 이걸 다시 펴줌
                         y = x2.flatten()[::20], # 20개씩 띄어서 
                         z = y2.flatten()[::20], 
                         opacity = 0.3, mode = 'markers')   # opacity는 투명도
data = [surface_1, surface_2]
pyo.iplot(data)

In [37]:
import numpy as np
import plotly.graph_objs as go  # plotly.graph_objects 라고 full name 안 써도 되나봄
X, Y = np.meshgrid(np.linspace(-4, 4, 50), np.linspace(-3, 3, 50))
X.shape  # 50 x 50 

(50, 50)

In [39]:
Z = np.sin(X**2 + Y**2)  # x^2 + y^2 을 input으로 가지는 sin 그래프
fig = go.Figure(data = [go.Scatter3d(x = X.flatten()[::10], 
                                    y = Y.flatten()[::10], 
                                    z = Z.flatten()[::10], 
                                    opacity = 0.3, mode = "markers")])  
                                    # 어떻게 이렇게 그려지는 지 모르겠음...... 
 fig.show()

In [40]:
Z = np.sin(X**2, Y**2)
Z1 = Z.copy()
Z1 = Z1 + np.random.rand(50, 50)  # 50 X 50의 random sample 
fig = go.Figure(data = [go.Surface(x = X, y = Y, z = Z), 
                        go.Scatter3d(x = X.flatten()[::10], 
                                     y = Y.flatten()[::10], 
                                     z = Z1.flatten()[::10], 
                                     opacity = 0.3, mode = "markers")])  
                         # 3차원 그래프를 overlap시킬 수 있음.
fig.show()

In [41]:
Z = np.sin(X**2+Y**2)
Z1 = Z.copy()
Z1 = Z1 + np.random.rand(50, 50)
Z2 = np.sin(X) + np.cos(Y)
fig = go.Figure(data = [go.Surface(x = X, y = Y, z = Z), 
                        go.Scatter3d(x = X.flatten()[::10], 
                                     y = Y.flatten()[::10], 
                                     z = Z1.flatten()[::10], 
                                     opacity = 0.3, mode = "markers"), 
                        go.Surface(x = X, y = Y, z = Z2)])
fig.show()