<a href="https://colab.research.google.com/github/Soy-code/ML_w_python/blob/master/Understanding_Python(6)_HSY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 6. 넘파이(numpy)

In [1]:
import numpy as np
np.array([1, 5, 7, 6])   # list data 는 data analysis에 쓰지 않음. 
                         # 1-d tensor 
                         # array data 로 만들어줌

array([1, 5, 7, 6])

In [2]:
np.array([1.25, 1, 5, 7])   # array는 data의 타입이 같아야 함. 

array([1.25, 1.  , 5.  , 7.  ])

In [3]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [4]:
np.ones([2, 3], dtype= float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.arange(0, 10, 2)  # 10은 포함 안 함

array([0, 2, 4, 6, 8])

In [6]:
np.linspace(0, 1, 5)   # 0하고 1 포함

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.random.seed(12) # seed number 설정

In [8]:
np.random.random((3, 3))  # ~ U(0, 1) 

array([[0.15416284, 0.7400497 , 0.26331502],
       [0.53373939, 0.01457496, 0.91874701],
       [0.90071485, 0.03342143, 0.95694934]])

In [9]:
np.random.normal(0, 1, (3, 3)) # ~ N(0, 1)

array([[-0.42069204, -0.7060276 ,  0.58535808],
       [ 0.13978644,  2.73781428,  1.11674795],
       [ 1.57453814, -0.08586679,  0.47673663]])

In [10]:
np.random.randint(0, 10, (3, 3))  # 0과 9 사이에서 정수 생성

array([[9, 0, 0],
       [9, 8, 9],
       [6, 1, 8]])

In [11]:
?np.random  # np.random에 대해 알려줌

In [12]:
rg = np.random.RandomState(40)  # 클래스를 rg로 객채화
rg.normal(0, 1, (3, 3))   ###  class에 대해 잘 모르겠음 ###

array([[-0.6075477 , -0.12613641, -0.68460636],
       [ 0.92871475, -1.84440103, -0.46700242],
       [ 2.29249034,  0.48881005,  0.71026699]])

In [13]:
# array의 객체화
import numpy as np
np.random.seed(1)
x = np.random.randint(10, size = (2, 3, 4))  # 3행 4열 행렬을 두 개 # 이건 그러면 3-d tensor? 
print(x) 
print(x.ndim)
print(x.shape)
print(x.size)
xx = x.flatten()
print(xx)

[[[5 8 9 5]
  [0 0 1 7]
  [6 9 2 4]]

 [[5 2 4 2]
  [4 7 7 9]
  [1 7 0 6]]]
3
(2, 3, 4)
24
[5 8 9 5 0 0 1 7 6 9 2 4 5 2 4 2 4 7 7 9 1 7 0 6]


In [14]:
# array 접근과 편집(slicing)
x = np.array([0, 3, 5, 2, 4, 6])  # 1-d tensor
print(x[1], x[2])

3 5


In [15]:
x1 = x[:, np.newaxis]   # 열벡터를 만듦
x1.ndim  # 2-d tensor
x2 = x[np.newaxis, :]  # 행벡터를 만듦
x2.ndim # 2-d tensor
print(x1)
print(x2)

[[0]
 [3]
 [5]
 [2]
 [4]
 [6]]
[[0 3 5 2 4 6]]


In [16]:
x3 = np.reshape(x, (6, 1))
x4 = np.reshape(x, (1, 6))
print(x3)
print(x4)

[[0]
 [3]
 [5]
 [2]
 [4]
 [6]]
[[0 3 5 2 4 6]]


In [17]:
x5 = x4.flatten()  # 2-d를 1-d로 핌
x5  # 다시 펴짐 

array([0, 3, 5, 2, 4, 6])

In [18]:
x[1:3]  #x[1], x[2]만 출력 

array([3, 5])

In [19]:
x[1:-2]  # 두 번째부터 끝에서 두 번째까지 

array([3, 5, 2])

In [20]:
# x[start : stop : step, 
#   start : stop : step, 
#   start : stop : step]
x[::2]  # 두 개씩 띄어서 

array([0, 5, 4])

In [21]:
x[::-1]  # 역순으로 

array([6, 4, 2, 5, 3, 0])

In [22]:
x[5::-2]  #  5(6번째) 시작해서 역순으로 두 개씩 띄어서? 

array([6, 2, 3])

In [23]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])  # 2-d tensor
x[:2, :2] # 행도 열도 두 개 까지

array([[1, 2],
       [4, 5]])

In [24]:
x[:, 0]  # 행은 다, 열은 하나만

array([1, 4, 7])

In [25]:
x[0, :]

array([1, 2, 3])

In [26]:
x[1, 2]  # 2행 3열 

6

In [27]:
x[0, 0] = 99   # list랑 차이 나는 거 확인, list는 x[0][0] 이렇게 해야함 
x

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [28]:
x1 = x[:2, :2]
x1

array([[99,  2],
       [ 4,  5]])

In [29]:
x1[0, 1] = 99
x1

array([[99, 99],
       [ 4,  5]])

In [30]:
print(x)   # x1을 수정하면 x에도 반영이 됨. (여기서부터 강의 들어야 함. 아마 1시간 20분? 정도)

[[99 99  3]
 [ 4  5  6]
 [ 7  8  9]]


In [31]:
id(x)

140389145486160

In [32]:
id(x1)   # 내가 x1에 수정을 했는데 x가 자동으로 그 수정된 걸 반영함. 
         # 근데 x1과 x의 주소는 다름

140389145487840

In [33]:
# 객체화 해서 객체를 수정하면 원래의 데이터가 바뀜
x1_copy = x[:2, :2].copy()   # copy라는 함수를 쓰면 수정을 해도 영향을 미치지 않음. 
x1_copy[0, 0] = 1000 
print(x1_copy) ; print(x)  # 바뀌지 않음. 

[[1000   99]
 [   4    5]]
[[99 99  3]
 [ 4  5  6]
 [ 7  8  9]]


### 6.1 numpy의 차원 변경, 분할, 덧붙이기

In [34]:
### 모든 객체 지우는 방법? 
### R에서 rm(list = ls())  같은 거 

In [35]:
# 차원변경
import numpy as np
x = np.array([1, 2, 3])
print(x) ; print(x.ndim)  # 1-d tensor

[1 2 3]
1


In [36]:
x.reshape((1, 3))  # 이거 1 X 3 matrix로 된 거 아닌가? 근데 print(x)하면 왜 안 되지? 
print(x) ; print(x.ndim)

[1 2 3]
1


In [37]:
# x.reshape() 한다고 x 자체가 바뀌는 건 아닌가 봄

print(x.reshape((1, 3)))  # 새로운 행이 생기는 거 : 2-d tensor
print(x[np.newaxis, :])
print(x.reshape((3, 1)))   # 새로운 열이 생기는 거  : 2-d tensor
print(x[:, np.newaxis]) 

[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [38]:
x = np.random.randint(10, size = (3, 3, 4))  # 3개의 3 X 4 행렬 : 3-d tensor
print(x)
print("===========================")
x1 = x.reshape((3, 12)) # 3 X 12 행렬로. 각 행을 옆으로 붙임. 12가 맞춰지게. 2-d tensor로
print(x1)
print("===========================")
x2 = x.reshape((-1, 12))  ### -1은 3을 대신함. 내가 꼭 obs 개수를 몰라도 되니까. 
print(x2)
print(np.shape(x2))

[[[9 9 7 6]
  [9 1 0 1]
  [8 8 3 9]]

 [[8 7 3 6]
  [5 1 9 3]
  [4 8 1 4]]

 [[0 3 9 2]
  [0 4 9 2]
  [7 7 9 8]]]
[[9 9 7 6 9 1 0 1 8 8 3 9]
 [8 7 3 6 5 1 9 3 4 8 1 4]
 [0 3 9 2 0 4 9 2 7 7 9 8]]
[[9 9 7 6 9 1 0 1 8 8 3 9]
 [8 7 3 6 5 1 9 3 4 8 1 4]
 [0 3 9 2 0 4 9 2 7 7 9 8]]
(3, 12)


In [39]:
# 분할 
x = [1, 2, 3, 4, 5, 6, 7, 8]
x1, x2, x3 = np.split(x, [2, 6])  # 3번 째, 7번 째에서 끊어라 
print(x1, x2, x3)

[1 2] [3 4 5 6] [7 8]


In [40]:
x1[0] = 100
print(x1)
print(x)   # split으로 분할 된 자료에서의 수정은 원래 데이터에 영향을 미치지 않음. 

[100   2]
[1, 2, 3, 4, 5, 6, 7, 8]


In [41]:
x = np.random.random((4, 4)) ; print(x)
print("---------------------------------------")
x1, x2 = np.vsplit(x, [2])  # 3번 째 vertical에서 끊음 
print(x1)
print("---------------------------------------")
print(x2)

[[0.46923853 0.09617226 0.90337017 0.11949047]
 [0.52479938 0.083623   0.91686133 0.91044838]
 [0.29893011 0.58438912 0.56591203 0.61393832]
 [0.95653566 0.26097898 0.23101542 0.53344849]]
---------------------------------------
[[0.46923853 0.09617226 0.90337017 0.11949047]
 [0.52479938 0.083623   0.91686133 0.91044838]]
---------------------------------------
[[0.29893011 0.58438912 0.56591203 0.61393832]
 [0.95653566 0.26097898 0.23101542 0.53344849]]


In [42]:
y1, y2 = np.hsplit(x, [2])  # 3번 째 horizontal에서 끊음
print(y1)
print("------------------------------------")
print(y2)
print("------------------------------------")

[[0.46923853 0.09617226]
 [0.52479938 0.083623  ]
 [0.29893011 0.58438912]
 [0.95653566 0.26097898]]
------------------------------------
[[0.90337017 0.11949047]
 [0.91686133 0.91044838]
 [0.56591203 0.61393832]
 [0.23101542 0.53344849]]
------------------------------------


In [43]:
# 덧붙이기 
x = np.array([1, 2]) # 1d
y = np.array([2, 3]) # 1d
z = np.array([4, 5]) # 1d
conc = np.concatenate([x, y, z]) 
conc  # 1d

array([1, 2, 2, 3, 4, 5])

In [44]:
### np.array로 3-d tensor 만드는 법??

In [45]:
xx = np.array([[1, 2, 3], [4, 5, 6]])
yy = np.array([[2, 4, 6], [8, 7, 6]])
print(xx)
print('----------')
print(yy)
print('----------')
conc1 = np.concatenate([xx, yy]) # 아래로 붙임 2d  # obsevation을 늘림
# np.concatenate([xx, yy], axis = 0) 과 같음 
print(conc1)
print('----------')
conc2 = np.concatenate([xx, yy], axis = 1)  # cbind
print(conc2)

[[1 2 3]
 [4 5 6]]
----------
[[2 4 6]
 [8 7 6]]
----------
[[1 2 3]
 [4 5 6]
 [2 4 6]
 [8 7 6]]
----------
[[1 2 3 2 4 6]
 [4 5 6 8 7 6]]


In [46]:
zz = np.array([55, 66, 77])
v1 = np.vstack([zz, xx])   # vertically stacking, 세로로 쌓기
print(v1)
print("----------------------")
v2 = np.concatenate([zz.reshape(1, 3), xx])  # 이거랑 같음 
print(v2)
# concatenate는 같은 차원끼리만 가능한 듯

[[55 66 77]
 [ 1  2  3]
 [ 4  5  6]]
----------------------
[[55 66 77]
 [ 1  2  3]
 [ 4  5  6]]


In [47]:
ww = np.array([[100], [200]])  
h1 = np.hstack([ww, xx])  # vertically stacking, 가로로 쌓기 
h1_1 = np.hstack([xx, ww])
print(h1, h1_1, sep="\n")  # 먼저 오는 게 먼저 출력 되는구먼 
print("-----------------------")
h2 = np.concatenate([ww.reshape(2, 1), xx], axis = 1)
print(h2)

[[100   1   2   3]
 [200   4   5   6]]
[[  1   2   3 100]
 [  4   5   6 200]]
-----------------------
[[100   1   2   3]
 [200   4   5   6]]


### 6.2 numpy 연산 

In [48]:
x = np.array([1, 2, 3, 4])
print(x + 3, 
      x - 3, 
      x * 3, 
      x / 3, 
      x ** 3, 
      -(0.5 * x + 1)**2, sep ="\n")

[4 5 6 7]
[-2 -1  0  1]
[ 3  6  9 12]
[0.33333333 0.66666667 1.         1.33333333]
[ 1  8 27 64]
[-2.25 -4.   -6.25 -9.  ]


In [49]:
print(np.exp(x))  # exponential e^1, e^2
print(np.power(3, x)) # 3^(x) 
print(np.log(x))  # log(x)  = loge(x)
print(np.log2(x))  # log2(x)
print(np.log10(x)) 

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 3  9 27 81]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]


In [50]:
M = np.ones((3, 3))
print(M)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [51]:
M1 = M + 1
print(M1)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [52]:
M1_1 = M[:2, :2]
M1_1[1, 1] = 4
M1_1   # 반영됨 

array([[1., 1.],
       [1., 4.]])

In [53]:
M = np.ones((3, 3)) 
a = np.array([1, 2, 3])
M2 = M + a
print(M2)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [54]:
a = np.arange(3)
print(a, a.ndim, sep = "\n")
b = np.arange(3)[:, np.newaxis]  # 열을 만듦 
print(b, b.ndim, sep = "\n")

[0 1 2]
1
[[0]
 [1]
 [2]]
2


In [55]:
print(a + b)  # shape이 다른데 덧셈을 할 수 있구나.... 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [56]:
# 기초통계량 계산
np.random.seed(13)
x = np.random.randint(10, size = (3, 4))  # 3 X 4 행렬 원소를 0~9까지의 정수로 
print(x)

[[2 0 0 6]
 [2 4 9 3]
 [4 2 6 5]]


In [57]:
print(np.sum(x))        # x 원소의 총 합계
print(np.min(x, axis = 1))   # 각 행의 최솟값
print(np.min(x, axis = 0))   # 각 열의 최솟값
print(np.mean(x, axis = 0))  # 각 열의 평균
print(np.std(x, axis = 0))  # 각 열의 표준편차

43
[0 2 2]
[2 0 0 3]
[2.66666667 2.         5.         4.66666667]
[0.94280904 1.63299316 3.74165739 1.24721913]


In [58]:
# standardize x 
# axis0 이므로 열마다 
x_std = (x - np.mean(x, axis = 0)) / np.std(x, axis = 0)
print(x_std)
print(np.mean(x))
print(np.mean(x_std))
print(np.var(x))
print(np.var(x_std))   # mean = 0, var = 1로 standardize 됨을 확인할 수 있음. 

[[-0.70710678 -1.22474487 -1.33630621  1.06904497]
 [-0.70710678  1.22474487  1.06904497 -1.33630621]
 [ 1.41421356  0.          0.26726124  0.26726124]]
3.5833333333333335
-5.551115123125783e-17
6.409722222222221
0.9999999999999999


### 6.2 논리 인덱싱(Boolean indexing)과 순서 정렬(sorting)

In [59]:
import numpy as np
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) ; print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [60]:
print(x >= 5)
print(np.sum(x >= 5))   # 5이상인 경우의 수 (행, 열 상관 없이 그냥 개수)
print(np.sum(x >= 5, axis = 1))  # 행 별로 몇 갠지 
print(np.sum(x >= 5, axis = 0))  # 열별로 몇 갠지 

[[False False False False]
 [ True  True  True  True]]
4
[0 4]
[1 1 1 1]


In [61]:
print(np.any(x > 100)) # 하나라도 100보다 큰 게 있는지
print(np.all(x < 7, axis = 0))  # 각 열에 해당되는 모든 원소가 7보다 작은지, 열별로 출력됨
print(np.all(x==100))  # 이건 모든 entry에 대해서

False
[ True  True False False]
False


In [62]:
# 논리 인덱싱
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12], 
              [13, 14, 15, 16]]) 
print(x)
print("----------------------------------")
y = np.array([1, 0, 1, 0]) 
print(y)
print("-----------------------------------")
print(x[y==0, :])  # y=0인 두 번째와 네 번째 행 & 모든 열
print("-----------------------------------")
print(x[:, y==0])  # y=0인 두 번째와 네 번째 열 & 모든 행 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
----------------------------------
[1 0 1 0]
-----------------------------------
[[ 5  6  7  8]
 [13 14 15 16]]
-----------------------------------
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [63]:
# array를 활용한 인덱싱
x = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
print(x)
print("----------------------------------")
idx1 = np.array([2, 3, 8])   
idx2 = np.array([[2, 1, 3], [5, 2, 7]])
x1 = x[idx1]  # 3, 4, 9번 째  
x2 = x[idx2]  # 3, 2, 4번 째 / 6, 3, 8번 째 출력 
print(x1)
print('----------------------------------')
print(x2)

[11 22 33 44 55 66 77 88 99]
----------------------------------
[33 44 99]
----------------------------------
[[33 22 44]
 [66 33 88]]


In [64]:
x = np.arange(12).reshape(-1, 4)
print(x)
print("===============================")
ind = np.array([1, 3])
print(ind)
print("==============================")
print(~ind) 
print(-ind)
print("==============================")
xx1 = x[:, ind]
xx2 = x[:, ~ind]
xx3 = x[:, -ind]
print(xx1, xx2, xx3, sep = "\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 3]
[-2 -4]
[-1 -3]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 2  0]
 [ 6  4]
 [10  8]]
[[ 3  1]
 [ 7  5]
 [11  9]]


In [65]:
# 인덱싱에서의 브로드캐스팅
x = np.arange(12).reshape((3, 4))
print(x)
x1 = np.arange(12).reshape((-1, 4))
print(x1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [66]:
y1 = np.array([1, 2, 2])
y2 = np.array([2, 0, 1])
print(y1[:, np.newaxis])  # 3 X 1 행렬 
print('---------------------------')
print(y2)    #  1-d tensor
print('---------------------------')
print(x[y1, y2])  # y1에 위치되어있는 행, y2에 위치되어있는 행. 
                  # (2, 3), (3, 1), (3, 2) : 6, 8, 9 
print('---------------------------')
print(x[y1[:, np.newaxis], y2])   # (1, 2, 2) X (2, 0, 1) 
                                  # (1, 2), (1, 0), (1, 1)
                                  # (2, 2), (2, 0), (2, 1)
                                  # (2, 2), (2, 0), (2, 1)
print('---------------------------')

[[1]
 [2]
 [2]]
---------------------------
[2 0 1]
---------------------------
[6 8 9]
---------------------------
[[ 6  4  5]
 [10  8  9]
 [10  8  9]]
---------------------------


In [67]:
# 순서 정렬 
x = np.array([2, 4, 3, 1, 5])
print(np.sort(x))

[1 2 3 4 5]


In [68]:
ind = np.argsort(x)  # sorting된 것들이 원래에 어떤 index를 가지고 있는지 
print(ind)

[3 0 2 1 4]


In [69]:
x = np.random.randint(1, 10, size = (2, 3, 4))  # 3 X 4행렬을 두 개 
x.ndim
print(x)

[[[5 3 1 4]
  [6 4 7 6]
  [2 3 9 9]]

 [[7 3 5 6]
  [8 4 6 9]
  [4 9 6 2]]]


In [70]:
x1 = x[:, -1, :]   # 모든 개수, 제일 끝 행, 모든 열 
x1

array([[2, 3, 9, 9],
       [4, 9, 6, 2]])